### ISSUE TITLE
auto migrate fails with belongs_to

### ISSUE THREAD

**Issue by makevoid** [datamapper/dm-constraints#15]
please clone this gist and run "bundle install" then run the ruby file (edit your mysql user and pass if needed)

git://gist.github.com/1381221.git

then uncomment the belongs_to line and run again, it should reproduce the error

gist link: https://gist.github.com/1381221

lighthouse issue:

http://datamapper.lighthouseapp.com/projects/20609/tickets/1236-sql-error-cant-create-table-during-migration-with-dm-constraints

**Comment by makevoid** [comment]
adding 

```
  property :list_id, Integer, :min => 1, :index => true
```

before the belongs_to fixes that but it's not ideal

**Comment by dkubb** [comment]
I've resolved this with edge dm-core and edge dm-constraints. I'm going to mark this as closed, but if you have any issues please add a comment and I'll reopen the issue.

**Comment by shingara** [comment]
I have the same issue with 1.2.0 version It's fix with which commit ?
